### ISSUE TITLE
SRE Transformation Leader

### ISSUE THREAD

**Issue by mcmanoj2001** [rod4n4m1/sre-manifesto#1]
# The SRE Manifesto

New Signatory Member

## Please fill out fields below

1. **Member name**: *Manoj Kuppam*

2. **Member GitHub userid**: **mcmanoj2001*

3. **Member e-mail**: *mcmanoj2001@gmail.com*

4. **Member company**: *Medline Industries*

5. **Member job title**: *Site Reliability Engineering Lead*

**Comment by rod4n4m1** [comment]
Added!
