### ISSUE TITLE
acceess request tSRE Manifesto

### ISSUE THREAD

**Issue by eddierocampo** [rod4n4m1/sre-manifesto#2]
# The SRE Manifesto

New Signatory Member

## Please fill out fields below

1. **Member name**: *eocampo*

2. **Member GitHub userid**: *33464546*

3. **Member e-mail**: *eddier.ocampo@gmail.com*

4. **Member company**: *Red Hat*

5. **Member job title**: *Consultant*

**Comment by rod4n4m1** [comment]
Added
